# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('date_added', models.DateField(default=datetime.datetime(2016, 2, 12, 10, 53, 57, 189289))),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
